# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3

install:
  - sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0
  - pip install -e .[dev]
  - pip install coveralls

script:
  - py.test --doctest-modules --cov=dikis src tests

after_success:
  - coveralls
